######################################################################
# Automatically generated by qmake (3.0) mer. juin 1 19:01:55 2022
######################################################################

TEMPLATE = app
TARGET = Projet_-c-
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++11 -g
LIBS += model/libBDD.a
LIBS += -lmysqlcppconn

# Input
HEADERS += FenetrePrincipale.h GrandeVue.h MiniVue.h ScenePlan.h
SOURCES += FenetrePrincipale.cpp main.cpp ScenePlan.cpp
